### ISSUE TITLE
Consider adding a reference to the rbmi package (under multiple imputation) - thank you very much!

### ISSUE THREAD

**Issue by wolbersm** [cran-task-views/MissingData#22]
- [rbmi](https://cran.r-project.org/web/packages/rbmi/): Implements standard and reference based multiple imputation for clinical trials with continuous longitudinal outcomes. Bayesian MI, maximum likelihood MI and conditional mean imputation (+re-sampling) are implemented. The package is described in Gower-Page et al (2022) <[doi: 10.21105/joss.04251](https://joss.theoj.org/papers/10.21105/joss.04251)>.

The package would fit under "multiple imputation" or even better under "Specific types of data".

**Comment by tuxette** [comment]
Thanks for the hint! However, our policy is to include only packages that have been on CRAN for more than one year. I'll keep an eye on this one and will include it in a future release.
