### ISSUE TITLE
New package to consider adding to CTV for missing data

### ISSUE THREAD

**Issue by pdwaggoner** [cran-task-views/MissingData#8]
Hi - Thanks for this excellent task view. It's been enormously helpful to me. 

I have recently authored a package, `hdimpute`, which I think contributes to the goal of this task view. Check it out here:

> https://github.com/pdwaggoner/hdImpute

Please let me know if this is appropriate and/or suggestions to get it into proper shape to be added. Thanks for considering!

**Comment by tuxette** [comment]
Hi @pdwaggoner ! Thank you for the suggestion: it is indeed something that we could consider for a later release of the TV. However, please note that we usually include packages that have been released on CRAN for more than a year (to avoid having to include and remove packages that are not stable enough too often). We are performing an entire review of the new packages each year (at the beginning of the year).
